# -*- coding: utf-8 -*-
"""random_forest_baseline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AILP98OgZWbQGVwzLV-9ItKd39wDgzkb
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

data = pd.read_csv("titanic.csv")
data = data.dropna(subset=['Age', 'Embarked'])  # drop missing
data['Sex'] = data['Sex'].map({'male': 0, 'female': 1})  # encode gender
data['Embarked'] = data['Embarked'].map({'S': 0, 'C': 1, 'Q': 2})  # encode port

features = ['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked']
X = data[features]
y = data['Survived']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model = RandomForestClassifier()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))